### ISSUE TITLE
shardingsphere and jakarta EE

### ISSUE THREAD

**Issue by trydofor** [trydofor/professional-wings#169]
```log
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
```

**Comment by trydofor** [comment]
* https://github.com/apache/shardingsphere/pull/27976
* https://github.com/apache/shardingsphere/issues/26896

**Comment by trydofor** [comment]
5.3.x

* https://github.com/apache/shardingsphere/issues/28233

**Comment by trydofor** [comment]
current workaround, waiting for JEE 9

```xml
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.8</version>
</dependency>
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>1.33</version>
</dependency>
```
