### ISSUE TITLE
ClassNotFoundException SpringBootAdminServerEnabledCondition

### ISSUE THREAD

**Issue by trydofor** [trydofor/professional-wings#170]
```log
Caused by: java.lang.ClassNotFoundException: de.codecentric.boot.admin.server.config.SpringBootAdminServerEnabledCondition
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:534) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:513) ~[na:na]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:304) ~[spring-core-6.1.2.jar:6.1.2]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:345) ~[spring-core-6.1.2.jar:6.1.2]
	... 25 common frames omitted
```

**Comment by trydofor** [comment]
```java
@ConditionalOnClass(SpringBootAdminServerEnabledCondition.class)
@Conditional(SpringBootAdminServerEnabledCondition.class)
```

do NOT put them together. spring evaluate them all
