### ISSUE TITLE
thisLazy pitfall

### ISSUE THREAD

**Issue by trydofor** [trydofor/professional-wings#236]
```log
org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'estimateServiceImpl' is expected to be of type 'com..common.service.order.impl.EstimateServiceImpl' but was actually of type 'jdk.proxy2.$Proxy145'
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.checkBeanNotOfRequiredType(DefaultListableBeanFactory.java:1899) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1876) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1406) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver$1.getTarget(ContextAnnotationAutowireCandidateResolver.java:103) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:701) ~[spring-aop-6.1.3.jar:6.1.3]
	at com..common.service.order.impl.EstimateServiceImpl$$SpringCGLIB$$0.estimateSendAsync(<generated>) ~[classes/:na]
	at com..common.service.order.impl.EstimateServiceImpl.estimate(EstimateServiceImpl.java:71) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
```

**Comment by trydofor** [comment]
For best practices and to avoid such issues:

* Use interfaces for beans wherever possible.
* Configure proxy preferences explicitly in your configuration.
* Understand the implications of different proxy mechanisms in Spring and design your services accordingly.

**Comment by trydofor** [comment]
check type at postProcessAfterInitialization,
throw IllegalStateException if unmatched
