### ISSUE TITLE
docker-compose.yml does not exist

### ISSUE THREAD

**Issue by trydofor** [trydofor/professional-wings#237]
```log
java.lang.IllegalArgumentException: Docker Compose file '../../observe/docker/docker-compose.yml' does not exist
at org.springframework.util.Assert.isTrue(Assert.java:129) ~[spring-core-6.1.3.jar:6.1.3]
at org.springframework.boot.docker.compose.core.DockerComposeFile.of(DockerComposeFile.java:112) ~[spring-boot-docker-compose-3.2.2.jar:3.2.2]

```

**Comment by trydofor** [comment]
pwd is difference,

* TestCase - professional-wings/wings/warlock-shadow
* Application - professional-wings

**Comment by trydofor** [comment]
TestingPropertyHelper.autoSetWingsRootDir
